### ISSUE TITLE
Weird error message when running tests

### ISSUE THREAD

**Issue by WNoort** [open-review/open-review#46]
When running the tests, I see the following warning/error:

```
Could not interpret environment variable 'foo' as boolean value.
Environment variable 'non-existent' must be specified.
```

**Comment by martijnbastiaan** [comment]
That's `get_bool()` which 'throws' an error (which is the expected behaviour in some tests). It needs to write to stdout as Django often suppresses exceptions if it encounters a failure when importing settings.py which leaves users guessing what's wrong.

Maybe we could suppress stdout in that particular TestCase, but I'm not sure about the gains. Closing for now!

**Comment by WNoort** [comment]
I truly hate it when the nice line of dots is interrupted by some weird message

**Comment by martijnbastiaan** [comment]
Haha! You're absolutely right.
