### ISSUE TITLE
LaTeX not well rendered with custom fonts

### ISSUE THREAD

**Issue by WNoort** [open-review/open-review#62]
![schermafdruk van 2014-04-01 12 07 34](https://cloud.githubusercontent.com/assets/5732655/2577901/c96f38d8-b985-11e3-9ced-2eca4801dfce.png)

Test by adding arxiv:1403.2840 to the database.

**Comment by martijnbastiaan** [comment]
Turns out this isn't an issue with custom fonts, but with custom LaTeX commands. The paper source includes:

```
\newcommand {\PP}{\mathbb{P}}
```

Sooo, they're mapping \PP to \mathbb{P}. Not really anyone’s fault (except maybe the authors of the paper), but we should think of a way to detect illegally formatted latex strings in order to prevent them from rendering incorrectly..

Closing? New issue?
