### ISSUE TITLE
Minor bug in Paper#trending method

### ISSUE THREAD

**Issue by thomasbrus** [open-review/open-review#76]
Not that important but the Paper#trending method doesn't yield any results if there are no papers that have been published in the last week. Of course this will never be a problem since our site will become super popular.

**Comment by martijnbastiaan** [comment]
Is this a bug or a feature? If we define trending papers to be in the last X weeks, then that's that. I'm cautious about introducing code which checks for these kind of circumstances as it undoubtedly introduce 'complex' logic and many queries. And of course `this will never be a problem since our site will become super popular.` :P

**Comment by thomasbrus** [comment]
Depends on the definition then I guess. However, I think it is not desirable that the trending doesn't return any papers at all.

Anyway.. it turns out that even with 10.000 papers and ~10 reviews per paper such a query can be run within ~0.05 seconds. This is the query I ran:

``` sql
SELECT papers.title, reviews.paper_id, count(*) AS number_of_reviews
FROM reviews
INNER JOIN papers
ON reviews.paper_id=papers.id
GROUP BY paper_id
ORDER BY number_of_reviews DESC
LIMIT 5;
```

```
$ time sqlite3 db/development.sqlite3 < trending.sql 
Paper #4|4|20
Paper #16|16|20
Paper #88|88|20
Paper #90|90|20
Paper #191|91|20

real    0m0.054s
user    0m0.046s
sys 0m0.007s
```

I tried implementing this with Django but couldn't figure it out, maybe someone else could take a look at it.

**Comment by shsdv** [comment]
I don't expect that performance will be a problem in the near future, and once it does become a problem we can switch to other ways of determining trending papers. For example by running a cronjob every X hours.

Nonetheless, I do think it is important to only count reviews that were written in the last few days when determining trending papers. Otherwise the 'trending' papers will likely always return the same set of papers (namely old papers with lots of reviews).

(BTW, I like that you actually tested to see how your query performs)

**Comment by thomasbrus** [comment]
Yes good point ;)

**Comment by martijnbastiaan** [comment]
Should we introduce code to automatically determine the interval (1 day, 2 days, 1 week, etc.) or do we think a constant (status quo) is just fine?

**Comment by shsdv** [comment]
If not a single review was written during the last week, I actually think it is fair to say we don't have any trending papers. IMO, a paper is not trending anymore if its last review is several weeks old.

I think the easiest and most consistent solution is to use a constant interval, and clearly inform the users about our definition of trending papers. We can for example inform our users by showing a hover text on the "Trending papers"-title, or displaying a small question mark or something like that. That way users will understand if no paper is trending because no reviews were written in the last week.

**Comment by martijnbastiaan** [comment]
+1
